#+TITLE: README for Fast Forward Feature Selection
#+AUTHOR: Adrien Lagrange
#+EMAIL: ad.lagrange@gmail.com

* Objectives
  The package provides the python codes to perform a fast forward feature selection using a Gaussian Mixture Model. The algorithm is based  on the  following papers  [[http://arxiv.org/abs/1501.00857]] and [[http://fauvel.mathieu.free.fr/data/ffs_gmm.pdf][Nonlinear parsimonious  feature selection for the  classification of
  hyperspectral images]]. And the code is inspired of [[https://github.com/mfauvel/FFFS]].

* Install
  Just download the  file ~npfs.py~ and import it with  python. It has been tested on linux, Ubuntu 14.04.

* Requirements
  Scipy needs to be installed.

  Scikit-learn: >=0.17

  For a fast processing, a good linear algebra library is required too. [[https://github.com/xianyi/OpenBLAS][Openblas]] is a good option.

* Usage
  See example of use in file ~test.py~ on artificial data, ~runTestFull.py~ on real data when using GMM classifier and ~runTestSelectionGMM.py~ on real data when using GMM classifier. (Database is not provided for the last two examples)

  Warning: Reference labels need to be integers from 1 to classNumbers.